(define (install-rational-package)
  ;; internal procedures
  (define (numer x) (car x))
  (define (denom x) (cdr x))
  (define (make-rat n d)
    (let ((g (gcd n d)))
      (cons (/ n g) (/ d g))))
  (define (add-rat x y)
    (make-rat (+ (* (numer x) (denom y))
		 (* (numer y) (denom x)))
	      (* (denom x) (denom y))))
  (define (sub-rat x y)
    (make-rat (- (* (numer x) (denom y))
		 (* (numer y) (denom x)))
	      (* (denom x) (denom y))))
  (define (mul-rat x y)
    (make-rat (* (numer x) (numer y))
	      (* (denom x) (denom y))))
  (define (div-rat x y)
    (make-rat (* (numer x) (denom y))
	      (* (denom x) (numer y))))
  (define (sqrt-rat x)
    (make-rat (sqrt (numer x))
	      (sqrt (denom x))))
  (define (atan-rat x y)
    (atan (/ (numer x) (denom x))
	  (/ (numer y) (denom y))))
  (define (sin-rat x)
    (sin (/ (numer x) (denom x))))
  (define (cos-rat x)
    (cos (/ (numer x) (denom x))))
  (define (square x)
    (* x x))
  (define (square-rat x y)
    (make-rat (square (numer x)) (square (denom x))))
  (define (equ? x y)
    (cond ((and (= (numer x) (numer y)) (= (denom x) (denom y))) #t)))
  (define (=zero? x)
    (= 0 (numer x)))
  ;; interface to rest of the system
  (define (tag x) (attach-tag 'rational x))
  (put 'add '(rational rational)
	(lambda (x y) (tag (add-rat x y))))
  (put 'sub '(rational rational)
	(lambda (x y) (tag (sub-rat x y))))
  (put 'mul '(rational rational)
	(lambda (x y) (tag (mul-rat x y))))
  (put 'div '(rational rational)
	(lambda (x y) (tag (div-rat x y))))
  (put 'make 'rational
       (lambda (n d) (tag (make-rat n d))))
  (put 'equ? '(rational rational) equ?)
  (put 'denom '(rational) denom)
  (put 'numer '(rational) numer)
  (put 'sqrt '(rational) (lambda (x) (tag (sqrt-rat x))))
  (put 'atan '(rational rational) (lambda (x) (tag (atan-rat x))))
  (put 'sin '(rational) (lambda (x) (tag (sin-rat x))))
  (put 'cos '(rational) (lambda (x) (tag (cos-rat x))))
  (put 'square '(rational) (lambda (x) (tag (square-rat x))))
  (put '=zero? '(rational) =zero?)
  'done)
(install-rational-package)
